server:
  port: 8084

spring:
  datasource:
    url: jdbc:h2:mem:catalog;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update  # dev; para prod usa migraciones
    show-sql: true
    properties:
      '[hibernate.format_sql]': true

springdoc:
  api-docs.path: /api-docs
  swagger-ui.path: /swagger-ui.html

clients:
  catalogo:
    base-url: http://localhost:8086
  usuario:
    base-url: http://localhost:8081
  resena:
    base-url: http://localhost:8085
  licencia:
    base-url: http://localhost:8083